<?php

/**
 * This is the model base class for the table "duty_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DutyType".
 *
 * Columns in table "duty_type" available as properties of the model,
 * followed by relations of table "duty_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $description
 * @property integer $lead_in_days
 * @property integer $duty_category_id
 * @property integer $generic_type_id
 * @property integer $deleted
 * @property integer $staff_id
 *
 * @property ClientToTaskTypeToDutyType[] $clientToTaskTypeToDutyTypes
 * @property Dutycategory $dutyCategory
 * @property GenericType $genericType
 * @property Staff $staff
 */
abstract class BaseDutyType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'duty_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DutyType|DutyTypes', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description, staff_id', 'required'),
			array('lead_in_days, duty_category_id, generic_type_id, deleted, staff_id', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>64),
			array('lead_in_days, duty_category_id, generic_type_id, deleted', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, description, lead_in_days, duty_category_id, generic_type_id, deleted, staff_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clientToTaskTypeToDutyTypes' => array(self::HAS_MANY, 'ClientToTaskTypeToDutyType', 'duty_type_id'),
			'dutyCategory' => array(self::BELONGS_TO, 'Dutycategory', 'duty_category_id'),
			'genericType' => array(self::BELONGS_TO, 'GenericType', 'generic_type_id'),
			'staff' => array(self::BELONGS_TO, 'Staff', 'staff_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'lead_in_days' => Yii::t('app', 'Lead In Days'),
			'duty_category_id' => null,
			'generic_type_id' => null,
			'deleted' => Yii::t('app', 'Deleted'),
			'staff_id' => null,
			'clientToTaskTypeToDutyTypes' => null,
			'dutyCategory' => null,
			'genericType' => null,
			'staff' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('lead_in_days', $this->lead_in_days);
		$criteria->compare('duty_category_id', $this->duty_category_id);
		$criteria->compare('generic_type_id', $this->generic_type_id);
		$criteria->compare('deleted', $this->deleted);
		$criteria->compare('staff_id', $this->staff_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}