<?php

/**
 * This is the model base class for the table "project_to_AuthAssignment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProjectToAuthAssignment".
 *
 * Columns in table "project_to_AuthAssignment" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $project_id
 * @property integer $AuthAssignment_id
 * @property integer $staff_id
 *
 */
abstract class BaseProjectToAuthAssignment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'project_to_AuthAssignment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProjectToAuthAssignment|ProjectToAuthAssignments', $n);
	}

	public static function representingColumn() {
		return array(
			'project_id',
			'AuthAssignment_id',
		);
	}

	public function rules() {
		return array(
			array('project_id, AuthAssignment_id, staff_id', 'required'),
			array('AuthAssignment_id, staff_id', 'numerical', 'integerOnly'=>true),
			array('project_id', 'length', 'max'=>10),
			array('project_id, AuthAssignment_id, staff_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'project_id' => null,
			'AuthAssignment_id' => null,
			'staff_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('project_id', $this->project_id);
		$criteria->compare('AuthAssignment_id', $this->AuthAssignment_id);
		$criteria->compare('staff_id', $this->staff_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}