<?php

/**
 * This is the model base class for the table "task_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TaskType".
 *
 * Columns in table "task_type" available as properties of the model,
 * followed by relations of table "task_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $description
 * @property integer $deleted
 * @property integer $staff_id
 * @property string $template_task_id
 *
 * @property Client[] $clients
 * @property Staff $staff
 * @property Task $templateTask
 */
abstract class BaseTaskType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'task_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TaskType|TaskTypes', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description, staff_id', 'required'),
			array('deleted, staff_id', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>64),
			array('template_task_id', 'length', 'max'=>10),
			array('deleted, template_task_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, description, deleted, staff_id, template_task_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clients' => array(self::MANY_MANY, 'Client', 'client_to_task_type(task_type_id, client_id)'),
			'staff' => array(self::BELONGS_TO, 'Staff', 'staff_id'),
			'templateTask' => array(self::BELONGS_TO, 'Task', 'template_task_id'),
		);
	}

	public function pivotModels() {
		return array(
			'clients' => 'ClientToTaskType',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'deleted' => Yii::t('app', 'Deleted'),
			'staff_id' => null,
			'template_task_id' => null,
			'clients' => null,
			'staff' => null,
			'templateTask' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('deleted', $this->deleted);
		$criteria->compare('staff_id', $this->staff_id);
		$criteria->compare('template_task_id', $this->template_task_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}