<?php

/**
 * This is the model base class for the table "generictaskcategory".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Generictaskcategory".
 *
 * Columns in table "generictaskcategory" available as properties of the model,
 * followed by relations of table "generictaskcategory" available as properties of the model.
 *
 * @property integer $id
 * @property integer $root
 * @property integer $lft
 * @property integer $rgt
 * @property integer $level
 * @property string $name
 * @property integer $deleted
 * @property integer $staff_id
 *
 * @property GenericTaskType[] $genericTaskTypes
 * @property Staff $staff
 */
abstract class BaseGenerictaskcategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'generictaskcategory';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Generictaskcategory|Generictaskcategories', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('lft, rgt, level, name, staff_id', 'required'),
			array('root, lft, rgt, level, deleted, staff_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>64),
			array('root, deleted', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, root, lft, rgt, level, name, deleted, staff_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'genericTaskTypes' => array(self::HAS_MANY, 'GenericTaskType', 'generic_task_category_id'),
			'staff' => array(self::BELONGS_TO, 'Staff', 'staff_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'root' => Yii::t('app', 'Root'),
			'lft' => Yii::t('app', 'Lft'),
			'rgt' => Yii::t('app', 'Rgt'),
			'level' => Yii::t('app', 'Level'),
			'name' => Yii::t('app', 'Name'),
			'deleted' => Yii::t('app', 'Deleted'),
			'staff_id' => null,
			'genericTaskTypes' => null,
			'staff' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('root', $this->root);
		$criteria->compare('lft', $this->lft);
		$criteria->compare('rgt', $this->rgt);
		$criteria->compare('level', $this->level);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('deleted', $this->deleted);
		$criteria->compare('staff_id', $this->staff_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}