<?php

/**
 * This is the model base class for the table "generic_task_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GenericTaskType".
 *
 * Columns in table "generic_task_type" available as properties of the model,
 * followed by relations of table "generic_task_type" available as properties of the model.
 *
 * @property integer $id
 * @property integer $client_to_task_type_client_id
 * @property integer $client_to_task_type_task_type_id
 * @property string $description
 * @property integer $generic_task_category_id
 * @property integer $generic_type_id
 * @property integer $deleted
 * @property integer $staff_id
 *
 * @property ClientToTaskType $clientToTaskTypeClient
 * @property ClientToTaskType $clientToTaskTypeTaskType
 * @property GenericType $genericType
 * @property Generictaskcategory $genericTaskCategory
 * @property Staff $staff
 * @property TaskToGenericTaskType[] $taskToGenericTaskTypes
 * @property TaskToGenericTaskType[] $taskToGenericTaskTypes1
 * @property TaskToGenericTaskType[] $taskToGenericTaskTypes2
 */
abstract class BaseGenericTaskType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'generic_task_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GenericTaskType|GenericTaskTypes', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('client_to_task_type_client_id, client_to_task_type_task_type_id, description, generic_type_id, staff_id', 'required'),
			array('client_to_task_type_client_id, client_to_task_type_task_type_id, generic_task_category_id, generic_type_id, deleted, staff_id', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>64),
			array('generic_task_category_id, deleted', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, client_to_task_type_client_id, client_to_task_type_task_type_id, description, generic_task_category_id, generic_type_id, deleted, staff_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clientToTaskTypeClient' => array(self::BELONGS_TO, 'ClientToTaskType', 'client_to_task_type_client_id'),
			'clientToTaskTypeTaskType' => array(self::BELONGS_TO, 'ClientToTaskType', 'client_to_task_type_task_type_id'),
			'genericType' => array(self::BELONGS_TO, 'GenericType', 'generic_type_id'),
			'genericTaskCategory' => array(self::BELONGS_TO, 'Generictaskcategory', 'generic_task_category_id'),
			'staff' => array(self::BELONGS_TO, 'Staff', 'staff_id'),
			'taskToGenericTaskTypes' => array(self::HAS_MANY, 'TaskToGenericTaskType', 'generic_task_type_client_to_task_type_client_id'),
			'taskToGenericTaskTypes1' => array(self::HAS_MANY, 'TaskToGenericTaskType', 'generic_task_type_client_to_task_type_task_type_id'),
			'taskToGenericTaskTypes2' => array(self::HAS_MANY, 'TaskToGenericTaskType', 'generic_task_type_description'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'client_to_task_type_client_id' => null,
			'client_to_task_type_task_type_id' => null,
			'description' => Yii::t('app', 'Description'),
			'generic_task_category_id' => null,
			'generic_type_id' => null,
			'deleted' => Yii::t('app', 'Deleted'),
			'staff_id' => null,
			'clientToTaskTypeClient' => null,
			'clientToTaskTypeTaskType' => null,
			'genericType' => null,
			'genericTaskCategory' => null,
			'staff' => null,
			'taskToGenericTaskTypes' => null,
			'taskToGenericTaskTypes1' => null,
			'taskToGenericTaskTypes2' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('client_to_task_type_client_id', $this->client_to_task_type_client_id);
		$criteria->compare('client_to_task_type_task_type_id', $this->client_to_task_type_task_type_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('generic_task_category_id', $this->generic_task_category_id);
		$criteria->compare('generic_type_id', $this->generic_type_id);
		$criteria->compare('deleted', $this->deleted);
		$criteria->compare('staff_id', $this->staff_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}