<?php

/**
 * This is the model base class for the table "day".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Day".
 *
 * Columns in table "day" available as properties of the model,
 * followed by relations of table "day" available as properties of the model.
 *
 * @property string $id
 * @property string $scheduled
 * @property string $preferred
 * @property string $earliest
 * @property string $planned
 * @property integer $staff_id
 *
 * @property Staff $staff
 * @property Task[] $tasks
 */
abstract class BaseDay extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'day';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Day|Days', $n);
	}

	public static function representingColumn() {
		return 'scheduled';
	}

	public function rules() {
		return array(
			array('staff_id', 'required'),
			array('staff_id', 'numerical', 'integerOnly'=>true),
			array('scheduled, preferred, earliest, planned', 'safe'),
			array('scheduled, preferred, earliest, planned', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, scheduled, preferred, earliest, planned, staff_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'staff' => array(self::BELONGS_TO, 'Staff', 'staff_id'),
			'tasks' => array(self::HAS_MANY, 'Task', 'day'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'scheduled' => Yii::t('app', 'Scheduled'),
			'preferred' => Yii::t('app', 'Preferred'),
			'earliest' => Yii::t('app', 'Earliest'),
			'planned' => Yii::t('app', 'Planned'),
			'staff_id' => null,
			'staff' => null,
			'tasks' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('scheduled', $this->scheduled, true);
		$criteria->compare('preferred', $this->preferred, true);
		$criteria->compare('earliest', $this->earliest, true);
		$criteria->compare('planned', $this->planned, true);
		$criteria->compare('staff_id', $this->staff_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}