<?php

/**
 * This is the model base class for the table "client".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Client".
 *
 * Columns in table "client" available as properties of the model,
 * followed by relations of table "client" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $deleted
 * @property integer $staff_id
 *
 * @property Staff $staff
 * @property TaskType[] $taskTypes
 * @property Project[] $projects
 */
abstract class BaseClient extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'client';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Client|Clients', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, staff_id', 'required'),
			array('deleted, staff_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>64),
			array('deleted', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, deleted, staff_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'staff' => array(self::BELONGS_TO, 'Staff', 'staff_id'),
			'taskTypes' => array(self::MANY_MANY, 'TaskType', 'client_to_task_type(client_id, task_type_id)'),
			'projects' => array(self::HAS_MANY, 'Project', 'client_id'),
		);
	}

	public function pivotModels() {
		return array(
			'taskTypes' => 'ClientToTaskType',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'deleted' => Yii::t('app', 'Deleted'),
			'staff_id' => null,
			'staff' => null,
			'taskTypes' => null,
			'projects' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('deleted', $this->deleted);
		$criteria->compare('staff_id', $this->staff_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}