<?php

/**
 * This is the model base class for the table "resourcecategory".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Resourcecategory".
 *
 * Columns in table "resourcecategory" available as properties of the model,
 * followed by relations of table "resourcecategory" available as properties of the model.
 *
 * @property integer $id
 * @property integer $root
 * @property integer $lft
 * @property integer $rgt
 * @property integer $level
 * @property integer $duty_category_id
 * @property string $description
 * @property integer $deleted
 *
 * @property ResourceType[] $resourceTypes
 * @property Dutycategory $dutyCategory
 */
abstract class BaseResourcecategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'resourcecategory';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Resourcecategory|Resourcecategories', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('lft, rgt, level, description', 'required'),
			array('root, lft, rgt, level, duty_category_id, deleted', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>64),
			array('root, duty_category_id, deleted', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, root, lft, rgt, level, duty_category_id, description, deleted', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'resourceTypes' => array(self::HAS_MANY, 'ResourceType', 'resource_category_id'),
			'dutyCategory' => array(self::BELONGS_TO, 'Dutycategory', 'duty_category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'root' => Yii::t('app', 'Root'),
			'lft' => Yii::t('app', 'Lft'),
			'rgt' => Yii::t('app', 'Rgt'),
			'level' => Yii::t('app', 'Level'),
			'duty_category_id' => null,
			'description' => Yii::t('app', 'Description'),
			'deleted' => Yii::t('app', 'Deleted'),
			'resourceTypes' => null,
			'dutyCategory' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('root', $this->root);
		$criteria->compare('lft', $this->lft);
		$criteria->compare('rgt', $this->rgt);
		$criteria->compare('level', $this->level);
		$criteria->compare('duty_category_id', $this->duty_category_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('deleted', $this->deleted);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}