<?php

/**
 * This is the model base class for the table "task_to_resource_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TaskToResourceType".
 *
 * Columns in table "task_to_resource_type" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $task_id
 * @property integer $resource_type_id
 * @property integer $quantity
 * @property integer $hours
 * @property string $start
 * @property integer $staff_id
 *
 */
abstract class BaseTaskToResourceType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'task_to_resource_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TaskToResourceType|TaskToResourceTypes', $n);
	}

	public static function representingColumn() {
		return array(
			'task_id',
			'resource_type_id',
		);
	}

	public function rules() {
		return array(
			array('task_id, resource_type_id, quantity, hours, staff_id', 'required'),
			array('resource_type_id, quantity, hours, staff_id', 'numerical', 'integerOnly'=>true),
			array('task_id', 'length', 'max'=>10),
			array('start', 'safe'),
			array('start', 'default', 'setOnEmpty' => true, 'value' => null),
			array('task_id, resource_type_id, quantity, hours, start, staff_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'task_id' => null,
			'resource_type_id' => null,
			'quantity' => Yii::t('app', 'Quantity'),
			'hours' => Yii::t('app', 'Hours'),
			'start' => Yii::t('app', 'Start'),
			'staff_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('task_id', $this->task_id);
		$criteria->compare('resource_type_id', $this->resource_type_id);
		$criteria->compare('quantity', $this->quantity);
		$criteria->compare('hours', $this->hours);
		$criteria->compare('start', $this->start, true);
		$criteria->compare('staff_id', $this->staff_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}