<?php

/**
 * This is the model base class for the table "material_to_task".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MaterialToTask".
 *
 * Columns in table "material_to_task" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $material_id
 * @property string $task_id
 * @property integer $quantity
 * @property integer $staff_id
 *
 */
abstract class BaseMaterialToTask extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'material_to_task';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MaterialToTask|MaterialToTasks', $n);
	}

	public static function representingColumn() {
		return array(
			'material_id',
			'task_id',
		);
	}

	public function rules() {
		return array(
			array('material_id, task_id, quantity, staff_id', 'required'),
			array('material_id, quantity, staff_id', 'numerical', 'integerOnly'=>true),
			array('task_id', 'length', 'max'=>10),
			array('material_id, task_id, quantity, staff_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'material_id' => null,
			'task_id' => null,
			'quantity' => Yii::t('app', 'Quantity'),
			'staff_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('material_id', $this->material_id);
		$criteria->compare('task_id', $this->task_id);
		$criteria->compare('quantity', $this->quantity);
		$criteria->compare('staff_id', $this->staff_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}