<?php

/**
 * This is the model base class for the table "dutycategory".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Dutycategory".
 *
 * Columns in table "dutycategory" available as properties of the model,
 * followed by relations of table "dutycategory" available as properties of the model.
 *
 * @property integer $id
 * @property integer $root
 * @property integer $lft
 * @property integer $rgt
 * @property integer $level
 * @property string $description
 * @property integer $deleted
 *
 * @property DutyType[] $dutyTypes
 * @property Resourcecategory[] $resourcecategories
 */
abstract class BaseDutycategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'dutycategory';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Dutycategory|Dutycategories', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('lft, rgt, level, description', 'required'),
			array('root, lft, rgt, level, deleted', 'numerical', 'integerOnly'=>true),
			array('description', 'length', 'max'=>64),
			array('root, deleted', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, root, lft, rgt, level, description, deleted', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'dutyTypes' => array(self::HAS_MANY, 'DutyType', 'duty_category_id'),
			'resourcecategories' => array(self::HAS_MANY, 'Resourcecategory', 'duty_category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'root' => Yii::t('app', 'Root'),
			'lft' => Yii::t('app', 'Lft'),
			'rgt' => Yii::t('app', 'Rgt'),
			'level' => Yii::t('app', 'Level'),
			'description' => Yii::t('app', 'Description'),
			'deleted' => Yii::t('app', 'Deleted'),
			'dutyTypes' => null,
			'resourcecategories' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('root', $this->root);
		$criteria->compare('lft', $this->lft);
		$criteria->compare('rgt', $this->rgt);
		$criteria->compare('level', $this->level);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('deleted', $this->deleted);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}