<?php

/**
 * This is the model base class for the table "generic_project_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GenericProjectType".
 *
 * Columns in table "generic_project_type" available as properties of the model,
 * followed by relations of table "generic_project_type" available as properties of the model.
 *
 * @property integer $id
 * @property integer $generic_type_id
 * @property integer $generic_project_category_id
 * @property integer $deleted
 * @property integer $staff_id
 *
 * @property GenericType $genericType
 * @property Genericprojectcategory $genericProjectCategory
 * @property Staff $staff
 * @property Project[] $projects
 */
abstract class BaseGenericProjectType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'generic_project_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GenericProjectType|GenericProjectTypes', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('generic_type_id, staff_id', 'required'),
			array('generic_type_id, generic_project_category_id, deleted, staff_id', 'numerical', 'integerOnly'=>true),
			array('generic_project_category_id, deleted', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, generic_type_id, generic_project_category_id, deleted, staff_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'genericType' => array(self::BELONGS_TO, 'GenericType', 'generic_type_id'),
			'genericProjectCategory' => array(self::BELONGS_TO, 'Genericprojectcategory', 'generic_project_category_id'),
			'staff' => array(self::BELONGS_TO, 'Staff', 'staff_id'),
			'projects' => array(self::MANY_MANY, 'Project', 'project_to_generic_project_type(generic_project_type_id, project_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'projects' => 'ProjectToGenericProjectType',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'generic_type_id' => null,
			'generic_project_category_id' => null,
			'deleted' => Yii::t('app', 'Deleted'),
			'staff_id' => null,
			'genericType' => null,
			'genericProjectCategory' => null,
			'staff' => null,
			'projects' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('generic_type_id', $this->generic_type_id);
		$criteria->compare('generic_project_category_id', $this->generic_project_category_id);
		$criteria->compare('deleted', $this->deleted);
		$criteria->compare('staff_id', $this->staff_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}