<?php

/**
 * This is the model base class for the table "client_to_task_type_to_duty_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ClientToTaskTypeToDutyType".
 *
 * Columns in table "client_to_task_type_to_duty_type" available as properties of the model,
 * followed by relations of table "client_to_task_type_to_duty_type" available as properties of the model.
 *
 * @property integer $id
 * @property integer $client_to_task_type_client_id
 * @property integer $client_to_task_type_task_type_id
 * @property integer $duty_type_id
 * @property string $AuthItem_name
 * @property integer $deleted
 * @property integer $staff_id
 *
 * @property ClientToTaskType $clientToTaskTypeClient
 * @property ClientToTaskType $clientToTaskTypeTaskType
 * @property DutyType $dutyType
 * @property AuthItem $authItemName
 * @property Staff $staff
 * @property Task[] $tasks
 */
abstract class BaseClientToTaskTypeToDutyType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'client_to_task_type_to_duty_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ClientToTaskTypeToDutyType|ClientToTaskTypeToDutyTypes', $n);
	}

	public static function representingColumn() {
		return 'AuthItem_name';
	}

	public function rules() {
		return array(
			array('client_to_task_type_client_id, client_to_task_type_task_type_id, duty_type_id, AuthItem_name, staff_id', 'required'),
			array('client_to_task_type_client_id, client_to_task_type_task_type_id, duty_type_id, deleted, staff_id', 'numerical', 'integerOnly'=>true),
			array('AuthItem_name', 'length', 'max'=>64),
			array('deleted', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, client_to_task_type_client_id, client_to_task_type_task_type_id, duty_type_id, AuthItem_name, deleted, staff_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'clientToTaskTypeClient' => array(self::BELONGS_TO, 'ClientToTaskType', 'client_to_task_type_client_id'),
			'clientToTaskTypeTaskType' => array(self::BELONGS_TO, 'ClientToTaskType', 'client_to_task_type_task_type_id'),
			'dutyType' => array(self::BELONGS_TO, 'DutyType', 'duty_type_id'),
			'authItemName' => array(self::BELONGS_TO, 'AuthItem', 'AuthItem_name'),
			'staff' => array(self::BELONGS_TO, 'Staff', 'staff_id'),
			'tasks' => array(self::MANY_MANY, 'Task', 'duty(client_to_task_type_to_duty_type_id, task_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'tasks' => 'Duty',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'client_to_task_type_client_id' => null,
			'client_to_task_type_task_type_id' => null,
			'duty_type_id' => null,
			'AuthItem_name' => null,
			'deleted' => Yii::t('app', 'Deleted'),
			'staff_id' => null,
			'clientToTaskTypeClient' => null,
			'clientToTaskTypeTaskType' => null,
			'dutyType' => null,
			'authItemName' => null,
			'staff' => null,
			'tasks' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('client_to_task_type_client_id', $this->client_to_task_type_client_id);
		$criteria->compare('client_to_task_type_task_type_id', $this->client_to_task_type_task_type_id);
		$criteria->compare('duty_type_id', $this->duty_type_id);
		$criteria->compare('AuthItem_name', $this->AuthItem_name);
		$criteria->compare('deleted', $this->deleted);
		$criteria->compare('staff_id', $this->staff_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}