<?php

/**
 * This is the model base class for the table "project_to_generic_project_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProjectToGenericProjectType".
 *
 * Columns in table "project_to_generic_project_type" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $project_id
 * @property integer $generic_project_type_id
 *
 */
abstract class BaseProjectToGenericProjectType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'project_to_generic_project_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProjectToGenericProjectType|ProjectToGenericProjectTypes', $n);
	}

	public static function representingColumn() {
		return array(
			'project_id',
			'generic_project_type_id',
		);
	}

	public function rules() {
		return array(
			array('project_id, generic_project_type_id', 'required'),
			array('generic_project_type_id', 'numerical', 'integerOnly'=>true),
			array('project_id', 'length', 'max'=>10),
			array('project_id, generic_project_type_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'project_id' => null,
			'generic_project_type_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('project_id', $this->project_id);
		$criteria->compare('generic_project_type_id', $this->generic_project_type_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}