<?php

/**
 * This is the model base class for the table "plan".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Plan".
 *
 * Columns in table "plan" available as properties of the model,
 * followed by relations of table "plan" available as properties of the model.
 *
 * @property integer $id
 * @property string $plan_name
 * @property string $url
 * @property integer $deleted
 * @property integer $staff_id
 *
 * @property Assembly[] $assemblies
 * @property Staff $staff
 */
abstract class BasePlan extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'plan';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Plan|Plans', $n);
	}

	public static function representingColumn() {
		return 'plan_name';
	}

	public function rules() {
		return array(
			array('plan_name, staff_id', 'required'),
			array('deleted, staff_id', 'numerical', 'integerOnly'=>true),
			array('plan_name', 'length', 'max'=>64),
			array('url', 'length', 'max'=>255),
			array('url, deleted', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, plan_name, url, deleted, staff_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'assemblies' => array(self::HAS_MANY, 'Assembly', 'plan_id'),
			'staff' => array(self::BELONGS_TO, 'Staff', 'staff_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'plan_name' => Yii::t('app', 'Plan Name'),
			'url' => Yii::t('app', 'Url'),
			'deleted' => Yii::t('app', 'Deleted'),
			'staff_id' => null,
			'assemblies' => null,
			'staff' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('plan_name', $this->plan_name, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('deleted', $this->deleted);
		$criteria->compare('staff_id', $this->staff_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}