<?php

/**
 * This is the model base class for the table "data_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DataType".
 *
 * Columns in table "data_type" available as properties of the model,
 * followed by relations of table "data_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $description
 * @property string $storage_table
 *
 * @property GenericType[] $genericTypes
 */
abstract class BaseDataType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'data_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DataType|DataTypes', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description, storage_table', 'required'),
			array('description, storage_table', 'length', 'max'=>64),
			array('id, description, storage_table', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'genericTypes' => array(self::HAS_MANY, 'GenericType', 'data_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'storage_table' => Yii::t('app', 'Storage Table'),
			'genericTypes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('storage_table', $this->storage_table, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}