<?php

/**
 * This is the model base class for the table "validation_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ValidationType".
 *
 * Columns in table "validation_type" available as properties of the model,
 * followed by relations of table "validation_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $description
 *
 * @property GenericType[] $genericTypes
 */
abstract class BaseValidationType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'validation_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ValidationType|ValidationTypes', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description', 'required'),
			array('id, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'genericTypes' => array(self::HAS_MANY, 'GenericType', 'validation_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'description' => Yii::t('app', 'Description'),
			'genericTypes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}